version: '3'

services:
  satoshi-shuffle:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: satoshi-shuffle
    restart: unless-stopped
    ports:
      - "5010:5010"
    volumes:
      - ../config:/app/config
      - ../logs:/app/logs
    networks:
      - satoshi-network
    environment:
      - TZ=UTC
      - RUNNING_IN_DOCKER=1
    cap_add:
      - CAP_SYS_PTRACE

networks:
  satoshi-network:
    driver: bridge
