version: '3'

services:
  satoshi-shuffle:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: satoshi-shuffle
    restart: unless-stopped
    ports:
      - "5010:5010"
    volumes:
      - ../config:/app/config
      - ../logs:/app/logs
    networks:
      - satoshi-network
    environment:
      - TZ=UTC
    cap_add:
      - SYS_PTRACE
      - SYS_KILL

networks:
  satoshi-network:
    driver: bridge
